### ISSUE TITLE
add a dark theme (far side of the moon)

### ISSUE THREAD

**Issue by lewxdev** [vanyauhalin/moondusttheme#1]
unsure if this is already on the roadmap, but it could be of benefit to others to also provide the choice of a dark theme (aptly named "Moondust: Far Side of the Moon")

**Comment by vanyauhalin** [comment]
Hi J. I am slowly working on a dark variant. Finding colors that suit my comfort is a bit challenging. But I am optimistic that I will discover them soon. By the way, you guessed right with the name, that is exactly what I planned to call it.

**Comment by des-d** [comment]
Love this theme! Great work, so much less distracting! 

Depending on the mood and environment I sometimes need something warmer and more comforting so what do you think about adding other planets for replacing blue shades with colours like green for example?

**Comment by vanyauhalin** [comment]
Hi, Desislav. Thank you for your words!

I did not think about it because the current state of the theme is enough for me. But I like the idea of adding more planets. However, it is not straightforward. The blue shades are woven into the entire theme, influencing the grays, which are subtly tinged with blue to maintain harmony. This effect is particularly noticeable in the dark variant. That is, adding a new independent plant will require creating all palettes from scratch.

In essence, I am fond of your idea, but I am not ready to take on its implementation yet. It is a complex task, and I would prefer first to finalize the dark variant and add more syntaxes. For example, widely used languages like Python and PHP are still unsupported. I will create a separate issue for this suggestion, which I can revisit in the future.

---

By the way, about the dark variant. It is almost ready.

<img width="982" alt="Screenshot 2024-07-09 at 07 54 25" src="https://github.com/vanyauhalin/moondusttheme/assets/56481109/8b020382-d260-478a-b92f-505978398da5">

**Comment by des-d** [comment]
Ivan take your time mate, you really invest yourself into these and its worth it and much appreciated! Dark theme is looking promising!

**Comment by Asmilex** [comment]
That looks absolutely lovely ❤️. Thank you for your work!

**Comment by Asmilex** [comment]
Hello! Any progress on the dark variant?

**Comment by vanyauhalin** [comment]
> Hello! Any progress on the dark variant?

Oh, sorry mate. I am stuck with this one. I have not opened the project since the summer. However, I hope to get back to it soon. Winter is coming (hehe), and the days are becoming shorter, so a dark theme is very much needed. As my eyes are beginning to hurt from the brightness in the evenings.

**Comment by Asmilex** [comment]
No issues here! I can totally relate, side projects sometimes get stuck inside the digital limbo. Take the time you need.

Either way, I've been using Moondust for months now —incredibly weird for me since I usually fall into theme-hopping mode from time to time— and the thought of the dark theme just crossed my mind again. If I have time, I'll try to add Python support, since that's my most used language.

Thank you for your efforts!

**Comment by vanyauhalin** [comment]
Hi everyone. I have just released version 0.7.0, which includes a dark variant of the theme. I would like to share a few words about it.
  
I generally like it, but I have some doubts. The challenge is that I developed the palette for the dark theme in the evenings and at night. It seems this was not the best idea because today, after working all day, I found the colors to be quite dull during daylight hours. I wanted to increase the brightness of the monitor several times, but it was already at the maximum level. However, as evening approached, this problem disappeared entirely. I usually use the dark theme only in the evenings and at night, so for me, it is not too critical. However, I understand that most developers prefer the dark theme by default. Most likely, in the future, I will slightly adjust the palette to make it brighter.
  
@Asmilex, this is for you. I have added Python support. I have wanted to do this for a long time and decided there is no reason to delay it any further.

**Comment by Asmilex** [comment]
Awn, that is so lovely, thank you so much ❤️. I'll play around with the dark version for a while, and come back to you once I have a good impression for the palette.

Thank you for your hard work!

**Comment by Asmilex** [comment]
A week has passed, and I've been using it on and off. For reference, I've been testing it on multiple monitors (from OLED to IPS), using Zed Mono Expanded at 13@400. OLED is UHD@42 (104.90 ppi).  

I also found that the contrast is ever so slightly low. While I did not increase the brightness, it required forcing my eyes to focus a bit more. Reading the file list from the primary side bar seems a bit more confortable than the editor font. I'm not sure whether this a result of the antialias or palette differences. Note that I have astigmatism (and that I should _really_ go and check my graduation), so bright elements on dark backgrounds tend to blend themselves.  

Either way, I'm very happy with it. It feels cozy, and complements the near side of the moon perfectly. I'll very happy obligued to your stylistic vision :heart:

**Comment by vanyauhalin** [comment]
Aw, so sweet! Special thanks for testing the theme on different monitors. I only have one display (my MacBook), so I did not even think about it. I will be reviewing the colors in the palette shortly. Would you mind if I tag you in the next release to hear your vision?

**Comment by Asmilex** [comment]
Sure, please and thank you!
